services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    command: >
      postgres
      -c wal_level=logical
      -c max_wal_size=1GB

  debezium:
    image: quay.io/debezium/server
    depends_on:
      - postgres
      - nginx-proxy
    ports:
      - "8080:8080"
    volumes:
      - "./debezium/config:/debezium/config"

  # Debezium Server DNS resolution doesn't like host.docker.internal
  # This nginx service proxies to the host's Vite dev server
  nginx-proxy:
    image: nginx:stable-alpine
    volumes:
      - ./debezium/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "5173:5173"
